### ISSUE TITLE
HTTPError: 400 on yahoo_query.get_league_players() call

### ISSUE THREAD

**Issue by austinbeauch** [uberfastman/yfpy#21]
`HTTPError: 400 Client Error: Bad Request for url: https://fantasysports.yahooapis.com/fantasy/v2/league/411.l.****/players;start=1425?format=json`

Not sure why this is popping up. Running the same script for a few days and only now is this throwing me an error. I don't think it's a data limit error since it's not 999 like the source comments suggest. 

Anyone experiencing the same thing? I might give it another 24hrs and then dig into it some more.

**Comment by uberfastman** [comment]
@Pensfan66 if you don't mind, could you open a separate issue for the token refresh? That seems like a reasonable update to make, but just for the sake of keeping things somewhat organized I'd appreciate having a separate thread for it.

**Comment by uberfastman** [comment]
@austinbeauch I've implemented a fix for this issue you've found in v4.1.1, in #23. Now when retrieving all players, if it fails on one of the requests it will attempt to individually retrieve all players in that request and simply skip failed players, and log the failures. Give it a whirl and see how it works for you. If any other problems arise regarding this, just reopen this issue.

**Comment by austinbeauch** [comment]
Looks like it's working, thanks a ton for your effort!!

**Comment by uberfastman** [comment]
@austinbeauch fantastic, glad we got it sorted! You did the hard leg work figuring it out after all, I just had to implement the workaround haha.
