### ISSUE TITLE
Error authorizing: "Developers: Please specify a valid client and submit again."

### ISSUE THREAD

**Issue by brnwx** [uberfastman/yfpy#28]
Yahoo produces an error in the browser when trying to create the token.json file: `Developers: Please specify a valid client and submit again.`

[Screenshot](https://drive.google.com/file/d/1dQErPgjMZuHzcWj3jyVRGHDtPqijacXo/view?usp=sharing)

My code:

```from pathlib import Path
from yfpy.query import YahooFantasySportsQuery
auth_dir = "."
query = YahooFantasySportsQuery(
    auth_dir, league_id="MY_LEAGE")
query.get_current_game_info()
```

Thanks!

**Comment by brnwx** [comment]
This happens when you don't choose Confidential Client

**Comment by wrenjr** [comment]
@brnwx thanks for the update!

**Comment by uberfastman** [comment]
@brnwx thanks for the update!
