### ISSUE TITLE
Error Importing YFPY packages: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by gman1594** [uberfastman/yfpy#29]
After upgrading to yfpy 8.0.7 from a much older version, I can no longer import the packages. 

It looks like in utils.py there is a variable called 'Dict', which, at least in my environment, is being interpreted as the 'type' rather than a variable, so that when 'Dict[str, Any]' is executed, an error is encountered.

I'm fairly new to this so my apologies if this has been brought up before or if this is an issue on my end.

![image](https://user-images.githubusercontent.com/29079542/185802983-3413dde9-bc84-4d97-8a70-795532e2dc17.png)

**Comment by gman1594** [comment]
Update: This issue was caused by me running Python 3.7. It looks like this leads to issues with the 'typing' type hint module. Running on Python 3.9 solved the issue.

**Comment by uberfastman** [comment]
Hmm, that's puzzling. It should work for Python 3.7, but to be fair I haven't extensively tested all Python versions. I did notice you're using Anaconda, which uses its own distribution of Python that isn't always identical to the official distributions, so maybe that could have been affecting it, but that's just speculation. 

Regardless, I'm glad you got it working! Let me know if anything else comes up.

**Comment by AsteroidOrangeJuice** [comment]
OrderedDict is not subscript-able until python 3.9.

https://peps.python.org/pep-0585/

I hit this issue on python 3.8.x as well.

**Comment by uberfastman** [comment]
@gman1594 @AsteroidOrangeJuice I've updated YFPY to v8.0.8 to fix the backwards compatibility with the type hints.
