### ISSUE TITLE
Unexpected TypeError

### ISSUE THREAD

**Issue by connormcole** [uberfastman/yfpy#31]
Hi,

I'm getting an unexpected TypeError when I try to run `import YahooFantasySportsQuery`, please see below screenshot. I was able to successfully setup my oauth file and connect to my yahoo account but am unable to run queries due to this error.

![type_error](https://user-images.githubusercontent.com/92554586/188760619-bc595bad-c5ab-4a9a-8234-d8b7ca4aa3e3.png)

Please let me know if any further info is needed to assist.

Thanks

**Comment by personjc** [comment]
Looks like this is caused by using python version below 3.9:
https://github.com/uberfastman/yfpy/issues/29

**Comment by uberfastman** [comment]
@connormcole @personjc I've updated YFPY to v8.0.8 to fix the type hints backwards compatibility with Python versions 3.7 and 3.8.
