### ISSUE TITLE
EXAMPLE.private.json Location

### ISSUE THREAD

**Issue by day1ok** [uberfastman/yfpy#42]
The file referenced in the readme has moved from test/integration/EXAMPLE.private.json to auth/EXAMPLE.private.json and should be updated accordingly.

**Comment by chmullens** [comment]
Came here to point this out myself, fortunately it's easy to find in the project.

**Comment by uberfastman** [comment]
Thanks for catching this @day1ok and @chmullens, updated the `README.md` in https://github.com/uberfastman/yfpy/pull/43.
