### ISSUE TITLE
New player stats data field?

### ISSUE THREAD

**Issue by bradbunce** [uberfastman/yfpy#56]
## Description of Issue
Got this when using the get_league_players query:

DEBUG - models.py - yfpy.models:128 - The Yahoo Fantasy Sports API includes 1 additional data fields for Player that are not included in YFPY: ['eligible_positions_to_add']

#### Yahoo Fantasy Sports League ID
263808

#### Yahoo Fantasy Sports League Privacy
Private

#### Operating System/Environment
macOS

**Comment by uberfastman** [comment]
Thanks for the heads up, this has been addressed in https://github.com/uberfastman/yfpy/releases/tag/v16.0.1
