### ISSUE TITLE
Learning oppurtunity

### ISSUE THREAD

**Issue by kylewilliams321** [uberfastman/yfpy#59]
I'm very novice at developing/programming but want to start the learning path. I'm a pretty adamant smart home user (home assistant) and would love to build an integration for Yahoo Sports.

If anyone would like to team up and take me under your wings I'd love to work with you to bring this project to life! Thanks.

**Comment by uberfastman** [comment]
Hi @kylewilliams321, always great to see people learning new things, and I'm certainly happy to see you doing so using YFPY, so I hope you continue to do so! That being said, I'm going to close this ticket, as this is meant as a location for people to post bugs and make feature requests. Please let me know if you have any questions about using YFPY!
